const ERROR_CODE: Record<string, number> = {
   NOT_FOUND: 404,
   INTERNAL_SERVER_ERROR: 500,
   UNAUTHORIZED: 401,
   AUTH_NOT_FOUND: 401,
   BAD_REQUEST: 400,
   FORBIDDEN: 403,
}

export default ERROR_CODE
