const ERROR = {
   NOT_FOUND: "NOT_FOUND",
   INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
   UNAUTHORIZED: "UNAUTHORIZED",
   BAD_REQUEST: "BAD_REQUEST",
   FORBIDDEN: "FORBIDDEN",
   AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
}

export default ERROR
